### ISSUE TITLE
Implement display of tasks in frontend

### ISSUE THREAD

**Issue by osklot12** [osklot12/idata2502-cloud-ci-cd#1]
Implement a view of available tasks in the application frontend. The user should be able too see the following information
for tasks:

- __header__: the task header briefly describing it
- __content__: a more detailed description of the task
- __created__: the date of creation of task
- __due/deadline__: the time at which the task is due
- __status__: the task status (e.g. _pending_, _done_, _in progress_)

**Comment by EpicDome** [comment]
Added a grid view of the task cards sorted with Pending, In progress and Done. Added a simple form for creation of tasks.
